{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.bgeo",
    "module": "bgeo-android",
    "version": "0.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.17.0.aar",
          "url": "bgeo-android-0.17.0.aar",
          "size": 347778,
          "sha512": "ad0cd244f6f4f85ff206a6951ff488796426c573c9f70f8fd0a925c970704d30dd52b2b9739276c3af90b8f0e6bcd5ae14dca7b0f93c17f5f0ff9e924711d137",
          "sha256": "1e241b7dd33a053a5f594d2618a59757c8431dbd89d464c8365607b7fe634979",
          "sha1": "453a4339d05a0b910d7bbad06a1b93d7e05547ff",
          "md5": "711f5c6d1396bf7f0dc2f041f8077b58"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "bgeo-android-0.17.0.aar",
          "url": "bgeo-android-0.17.0.aar",
          "size": 347778,
          "sha512": "ad0cd244f6f4f85ff206a6951ff488796426c573c9f70f8fd0a925c970704d30dd52b2b9739276c3af90b8f0e6bcd5ae14dca7b0f93c17f5f0ff9e924711d137",
          "sha256": "1e241b7dd33a053a5f594d2618a59757c8431dbd89d464c8365607b7fe634979",
          "sha1": "453a4339d05a0b910d7bbad06a1b93d7e05547ff",
          "md5": "711f5c6d1396bf7f0dc2f041f8077b58"
        }
      ]
    }
  ]
}
